### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sumachaa** [postmanlabs/raml1-to-postman#22]
Is there an example of how we can use this. We have a raml folder (with #%RAML 1.0). 
How can we this code to convert those to postman collection?

**Comment by VShingala** [comment]
@sumachaa We will be updating README.md with better description in future release. For now you can follow this steps.

## Using the converter as a NodeJS module

In order to use the convert in your node application, you need to import the package using `require`.

```javascript
var Converter = require('raml1-to-postman')
```

The converter provides the following functions:

### Convert

The convert function takes in your RAML 1.0 specification and converts it to a Postman collection.

Signature: `convert (data, options, callback);`

**data:**

```javascript
{ type: 'file', data: 'filepath' }
OR
{ type: 'string', data: '<entire RAML 1.0 Specification string>' }
OR
{ type: 'folder', data: [Array of Objects with fileName property and file-path as it's value] }
```

**options:**
```javascript
{
  collapseFolders: true,
  requestParametersResolution: 'schema',
  exampleParametersResolution: 'example'
}
/*
All three properties are optional. Defaults will be used for no options provided. For now you can pass this as empty object.
*/
```

**callback:**
```javascript
function (err, result) {
  /*
  result = {
    result: true,
    output: [
      {
        type: 'collection',
        data: {..collection object..}
      }
    ]
  }
  */
}
```

### ConversionResult

- `result` - Flag responsible for providing a status whether the conversion was successful or not 

- `reason` - Provides the reason for an unsuccessful conversion, defined only if result: false

- `output` - Contains an array of Postman objects, each one with a `type` and `data`. The only type currently supported is `collection`.



### Sample Usage:
```javascript
var fs = require('fs'),

Converter = require('raml1-to-postman'),
ramlSpec = fs.readFileSync('sample-spec.raml', {encoding: 'UTF8'});

Converter.convert({ type: 'string', data: ramlSpec },
  {}, (err, conversionResult) => {
    if (!conversionResult.result) {
      console.log('Could not convert', conversionResult.reason);
    }
    else {
      console.log('The collection object is: ', conversionResult.output[0].data);
    }
  }
);
```

### Validate Function

The validate function is meant to ensure that the data that is being passed to the [convert function](#convert-function) is a valid RAML 1.0 Spec.

The validate function is synchronous and returns a status object which conforms to the following schema

#### Validation object schema

```javascript
{
  type: 'object',
  properties: {
    result: { type: 'boolean'},
    reason: { type: 'string' }
  },
  required: ['result']
}
```

##### Validation object explanation
- `result` - true if the data looks like RAML 1.0 and can be passed to the convert function

- `reason` - Provides a reason for an unsuccessful validation of the specification

**Comment by VShingala** [comment]
PR to update Readme [here](https://github.com/postmanlabs/raml1-to-postman/pull/23) includes example and detailed usage. So closing this fo now.
